# Generated by Django 4.2.4 on 2023-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
                ('bpm', models.IntegerField()),
                ('key', models.TextField()),
                ('path', models.TextField()),
                ('del_field', models.TextField(default='delete')),
            ],
        ),
    ]
