# Generated by Django 4.2.4 on 2023-08-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='path',
            new_name='full_path',
        ),
    ]
